Update comment.yml

diff --git a/.github/workflows/comment.yml b/.github/workflows/comment.yml
--- a/.github/workflows/comment.yml
+++ b/.github/workflows/comment.yml
@@ -16,21 +16,28 @@ jobs:
     - name: check user access with mgs
       run: |      
         #!/bin/bash
-        # Get the owner and repository name from the GITHUB_REPOSITORY environment variable
-        IFS='/' read -r -a array <<< "$GITHUB_REPOSITORY"
-        owner="${array[0]}"
-        repo="${array[1]}"
-        # Get the user who triggered the workflow
-        sender_login=$(echo "$GITHUB_EVENT_PATH" | jq -r .sender.login)
-        # Get the user's permissions on the repository
-        permissions=$(curl -s -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" "https://api.github.com/repos/$owner/$repo/collaborators/$sender_login/permission")
+        set -e  # exit immediately if a command exits with a non-zero status
+        set -x  # enable debugging output
+
+        # Extract the repository owner and name from the event payload
+        REPO_OWNER=$(echo "${GITHUB_REPOSITORY}" | cut -d "/" -f 1)
+        REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d "/" -f 2)
+
+        # Get the username of the user who created the comment
+        SENDER=$(jq -r ".comment.user.login" "$GITHUB_EVENT_PATH")
+
+        # Get the permissions of the user who created the comment
+        PERMISSIONS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/collaborators/$SENDER/permission" | jq -r ".permission")
+
         # Check if the user has write permission
-        if [[ $(echo "$permissions" | jq -r .permission) != "admin" && $(echo "$permissions" | jq -r .permission) != "write" ]]; then
-          # Add a comment to the PR
-          pr_number=$(echo "$GITHUB_EVENT_PATH" | jq -r .issue.number)
-          curl -s -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" -X POST -d "{\"body\":\"@${sender_login} You are not authorized to trigger this workflow. Only users with write permission can trigger this workflow.\"}" "https://api.github.com/repos/$owner/$repo/issues/$pr_number/comments"
-          exit 1
+        if [ "$PERMISSIONS" == "write" ]; then
+          echo "User has write permission"
+        else
+          echo "User does not have write permission"
+          pr_number=$(jq -r ".issue.number" "$GITHUB_EVENT_PATH")
+          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -X POST -d "{\"body\":\"@$SENDER You are not authorized to trigger this workflow. Only users with write permission can trigger this workflow.\"}" "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$pr_number/comments"
         fi
+
 
       
     - name: check user access
