Updated values.yaml and install.sh files

diff --git a/K8s-deployment/Charts/redis/values.yaml b/K8s-deployment/Charts/redis/values.yaml
--- a/K8s-deployment/Charts/redis/values.yaml
+++ b/K8s-deployment/Charts/redis/values.yaml
@@ -423,25 +423,20 @@ redis:
   command: []
   ## @param redis.args Arguments for the provided command if needed
   ##
-  args: []
-  ## @param redis.updateStrategy.type Argo Workflows statefulset strategy type
-  ## ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies
-  ##
-  updateStrategy:
-    ## StrategyType
-    ## Can be set to RollingUpdate or OnDelete
-    ##
-    type: RollingUpdate
-    ## @param redis.updateStrategy.rollingUpdate.partition Partition update strategy
-    ## https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#partitions
-    ##
-    rollingUpdate:
-      partition: 0
-
-  ## @param redis.podManagementPolicy Statefulset Pod management policy, it needs to be Parallel to be able to complete the cluster join
-  ## Ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-management-policies
-  ##
-  podManagementPolicy: Parallel
+  args:
+   - |
+       # Backwards compatibility change
+       if ! [[ -f /opt/bitnami/redis/etc/redis.conf ]]; then
+           echo COPYING FILE
+           cp  /opt/bitnami/redis/etc/redis-default.conf /opt/bitnami/redis/etc/redis.conf
+       fi
+       pod_index=($(echo "$POD_NAME" | tr "-" "\n"))
+       pod_index="${pod_index[-1]}"
+       if [[ "$pod_index" == "0" ]]; then
+          export REDIS_CLUSTER_CREATOR="yes"
+          export REDIS_CLUSTER_REPLICAS="1"
+       fi
+       /opt/bitnami/scripts/redis-cluster/entrypoint.sh /opt/bitnami/scripts/redis-cluster/run.sh --loadmodule /usr/local/lib/rejson.so 
   ## @param redis.hostAliases Deployment pod host aliases
   ## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
   ##
@@ -501,7 +496,10 @@ redis:
   ## @param redis.configmap Additional Redis&reg; configuration for the nodes
   ## ref: https://redis.io/topics/config
   ##
-  configmap: ""
+  configmap: |-
+    cluster-require-full-coverage no 
+    cluster-node-timeout 90000  
+    tcp-keepalive 120
   ## @param redis.extraEnvVars An array to add extra environment variables
   ## For example:
   ##  - name: BEARER_AUTH
@@ -656,7 +654,73 @@ updateJob:
   command: []
   ## @param updateJob.args Container args (using container default if not set)
   ##
-  args: []
+  args: 
+    - |
+      echo "Node Type = {{.Values.updateJob.nodeType}}"
+      . /opt/bitnami/scripts/libnet.sh
+      . /opt/bitnami/scripts/libos.sh
+      # Backwards compatibility change
+      if ! [[ -f /opt/bitnami/redis/etc/redis.conf ]]; then
+          cp /opt/bitnami/redis/etc/redis-default.conf /opt/bitnami/redis/etc/redis.conf
+      fi
+      firstNodeIP=$(wait_for_dns_lookup {{ template "common.names.fullname" . }}-0.{{ template "common.names.fullname" . }}-headless 120 5)
+      {{- if eq .Values.updateJob.nodeType "slave" }}
+        echo "creating slave for master {{ .Values.updateJob.masterID}}"
+        newNodeIndex="{{.Values.cluster.update.currentNumberOfNodes}}"
+        masterID="{{ .Values.updateJob.masterID}}"
+        newNodeIP=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-${newNodeIndex}.{{ template "common.names.fullname" . }}-headless" 120 5)
+        echo "node IP = $newNodeIP"
+        {{- if .Values.tls.enabled }}
+        echo "tls.enabled"
+        while [[ $(redis-cli -h "$newNodeIP" -p "$REDIS_TLS_PORT" --tls --cert ${REDIS_TLS_CERT_FILE} --key ${REDIS_TLS_KEY_FILE} --cacert ${REDIS_TLS_CA_FILE} ping) != 'PONG' ]]; do
+        {{- else }}
+        echo "tls.disabled"
+        while [[ $(redis-cli -h "$newNodeIP" -p "$REDIS_PORT" ping) != 'PONG' ]]; do
+        {{- end }}
+          echo "Node $newNodeIP not ready, waiting for all the nodes to be ready..."
+          newNodeIP=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-${newNodeIndex}.{{ template "common.names.fullname" . }}-headless" 120 5)
+          sleep 5
+        done
+        {{- if .Values.tls.enabled }}
+        while ! redis-cli --cluster add-node --tls --cert ${REDIS_TLS_CERT_FILE} --key ${REDIS_TLS_KEY_FILE} --cacert ${REDIS_TLS_CA_FILE} "${newNodeIP}:${REDIS_TLS_PORT}" "${firstNodeIP}:${REDIS_TLS_PORT}" --cluster-slave --cluster-master-id ${masterID[@]}; do
+        {{- else }}
+        echo "adding node to cluster"
+        while ! redis-cli --cluster add-node "${newNodeIP}:${REDIS_PORT}" "${firstNodeIP}:${REDIS_PORT}" --cluster-slave --cluster-master-id ${masterID[@]}; do
+        {{- end }}
+          echo "Add-node ${newNodeIndex} ${newNodeIP} failed, retrying"
+          sleep 5
+          firstNodeIP=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-0.{{ template "common.names.fullname" . }}-headless" 120 5)
+          newNodeIP=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-${newNodeIndex}.{{ template "common.names.fullname" . }}-headless" 120 5)
+        done
+      {{- else if eq .Values.updateJob.nodeType "master"}}
+        for node in $(seq $((1+{{ .Values.cluster.update.currentNumberOfNodes }})) {{ .Values.cluster.nodes }}); do
+          newNodeIndex="$(($node - 1))"
+          newNodeIP=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-${newNodeIndex}.{{ template "common.names.fullname" . }}-headless" 120 5)
+          {{- if .Values.tls.enabled }}
+          while [[ $(redis-cli -h "$newNodeIP" -p "$REDIS_TLS_PORT" --tls --cert ${REDIS_TLS_CERT_FILE} --key ${REDIS_TLS_KEY_FILE} --cacert ${REDIS_TLS_CA_FILE} ping) != 'PONG' ]]; do
+          {{- else }}
+          while [[ $(redis-cli -h "$newNodeIP" -p "$REDIS_PORT" ping) != 'PONG' ]]; do
+          {{- end }}
+            echo "Node $newNodeIP not ready, waiting for all the nodes to be ready..."
+            newNodeIP=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-${newNodeIndex}.{{ template "common.names.fullname" . }}-headless" 120 5)
+            sleep 5
+          done
+          slave=()
+          if (( $REDIS_CLUSTER_REPLICAS >= 1 )) && (( newNodeIndex % (( $REDIS_CLUSTER_REPLICAS + 1 )) )); then
+            slave+=("--cluster-slave")
+          fi
+          {{- if .Values.tls.enabled }}
+          while ! redis-cli --cluster add-node --tls --cert ${REDIS_TLS_CERT_FILE} --key ${REDIS_TLS_KEY_FILE} --cacert ${REDIS_TLS_CA_FILE} "${newNodeIP}:${REDIS_TLS_PORT}" "${firstNodeIP}:${REDIS_TLS_PORT}" ${slave[@]}; do
+          {{- else }}
+          while ! redis-cli --cluster add-node "${newNodeIP}:${REDIS_PORT}" "${firstNodeIP}:${REDIS_PORT}" ${slave[@]}; do
+          {{- end }}
+            echo "Add-node ${newNodeIndex} ${newNodeIP} failed, retrying"
+            sleep 5
+            firstNodeIP=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-0.{{ template "common.names.fullname" . }}-headless" 120 5)
+            newNodeIP=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-${newNodeIndex}.{{ template "common.names.fullname" . }}-headless" 120 5)
+          done
+        done
+        {{- end }}
   ## @param updateJob.hostAliases Deployment pod host aliases
   ## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
   ##
@@ -1015,10 +1079,15 @@ metrics:
 sysctlImage:
   ## @param sysctlImage.enabled Enable an init container to modify Kernel settings
   ##
-  enabled: false
+  enabled: true
   ## @param sysctlImage.command sysctlImage command to execute
   ##
-  command: []
+  command:
+    - /bin/sh
+    - -c
+    - |-
+      sysctl -w net.core.somaxconn=10000
+      echo never > /host-sys/kernel/mm/transparent_hugepage/enabled
   ## @param sysctlImage.registry [default: REGISTRY_NAME] sysctlImage Init container registry
   ## @param sysctlImage.repository [default: REPOSITORY_NAME/os-shell] sysctlImage Init container repository
   ## @skip sysctlImage.tag sysctlImage Init container tag
@@ -1041,7 +1110,7 @@ sysctlImage:
   pullSecrets: []
   ## @param sysctlImage.mountHostSys Mount the host `/sys` folder to `/host-sys`
   ##
-  mountHostSys: false
+  mountHostSys: true
   ## Containers Security Context
   ## @param sysctlImage.containerSecurityContext.enabled Enable Containers' Security Context
   ## @param sysctlImage.containerSecurityContext.runAsUser User ID for the containers.
